model:
  weights: elements
  img: page
  confidence: 0.33
  iou: 0.45
  classes:
  agnostic_nms:
  max_det: 100
  line_thickness: 3
  nc:
  backbone:
    [ [ -1, 1, Focus, [ 64, 3 ] ],
      [ -1, 1, Conv, [ 128, 3, 2 ] ],
      [ -1, 3, BottleneckCSP, [ 128 ] ],
      [ -1, 1, Conv, [ 256, 3, 2 ] ],
      [ -1, 9, BottleneckCSP, [ 256 ] ],
      [ -1, 1, Conv, [ 512, 3, 2 ] ],
      [ -1, 9, BottleneckCSP, [ 512 ] ],
      [ -1, 1, Conv, [ 1024, 3, 2 ] ],
      [ -1, 1, SPP, [ 1024, [ 5, 9, 13 ] ] ],
      [ -1, 3, BottleneckCSP, [ 1024, False ] ],
    ]
  head:
    [ [ -1, 1, Conv, [ 512, 1, 1 ] ],
      [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
      [ [ -1, 6 ], 1, Concat, [ 1 ] ],
      [ -1, 3, BottleneckCSP, [ 512, False ] ],
      [ -1, 1, Conv, [ 256, 1, 1 ] ],
      [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
      [ [ -1, 4 ], 1, Concat, [ 1 ] ],
      [ -1, 3, BottleneckCSP, [ 256, False ] ],
      [ -1, 1, Conv, [ 256, 3, 2 ] ],
      [ [ -1, 14 ], 1, Concat, [ 1 ] ],
      [ -1, 3, BottleneckCSP, [ 512, False ] ],
      [ -1, 1, Conv, [ 512, 3, 2 ] ],
      [ [ -1, 10 ], 1, Concat, [ 1 ] ],
      [ -1, 3, BottleneckCSP, [ 1024, False ] ],
      [ [ 17, 20, 23 ], 1, Detect, [ nc, anchors ] ],
    ]
  depth_multiple: 0.33
  width_multiple: 0.50
  anchors:
    - [ 10,13, 16,30, 33,23 ]
    - [ 30,61, 62,45, 59,119 ]
    - [ 116,90, 156,198, 373,326 ]
  n:
    ['text_field', 'button', 'checkbox', 'dropdown', 'link', 'radio_button']
  pad:
remote:
  host: 120.78.133.207
  port: 80
command_parameter:
  environment: QA
  browser:
  test:
  exclude_test:
  tag:
  keyword: login
  marker:
  mobile_platform:
  device:
  log_level: DEBUG